mvc-rpg/Controllers/EnemiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using mvc_rpg.Data;
using mvc_rpg.Entities;

namespace mvc_rpg.Controllers
{
    public class EnemiesController : Controller
    {
        private readonly RPGContext _context;

        public EnemiesController(RPGContext context)
        {
            _context = context;
        }

        // GET: Enemies
        public async Task<IActionResult> Index()
        {
            var rPGContext = _context.Enemies.Include(e => e.EnemyType);
            return View(await rPGContext.ToListAsync());
        }

        // GET: Enemies/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var enemy = await _context.Enemies
                .Include(e => e.EnemyType)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (enemy == null)
            {
                return NotFound();
            }

            return View(enemy);
        }

        // GET: Enemies/Create
        public IActionResult Create()
        {
            ViewData["EnemyTypeID"] = new SelectList(_context.EnemyTypes, "ID", "Name");
            return View();
        }

        // POST: Enemies/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Name,isAlive,EnemyTypeID")] Enemy enemy)
        {
            if (ModelState.IsValid)
            {
                _context.Add(enemy);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["EnemyTypeID"] = new SelectList(_context.EnemyTypes, "ID", "ID", enemy.EnemyTypeID);
            return View(enemy);
        }

        // GET: Enemies/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var enemy = await _context.Enemies.FindAsync(id);
            if (enemy == null)
            {
                return NotFound();
            }
            ViewData["EnemyTypeID"] = new SelectList(_context.EnemyTypes, "ID", "ID", enemy.EnemyTypeID);
            return View(enemy);
        }

        // POST: Enemies/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Name,isAlive,EnemyTypeID")] Enemy enemy)
        {
            if (id != enemy.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(enemy);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EnemyExists(enemy.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["EnemyTypeID"] = new SelectList(_context.EnemyTypes, "ID", "ID", enemy.EnemyTypeID);
            return View(enemy);
        }

        // GET: Enemies/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var enemy = await _context.Enemies
                .Include(e => e.EnemyType)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (enemy == null)
            {
                return NotFound();
            }

            return View(enemy);
        }

        // POST: Enemies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var enemy = await _context.Enemies.FindAsync(id);
            if (enemy != null)
            {
                _context.Enemies.Remove(enemy);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EnemyExists(int id)
        {
            return _context.Enemies.Any(e => e.ID == id);
        }
    }
}

mvc-rpg/Controllers/ItemTypesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using mvc_rpg.Data;
using mvc_rpg.Entities;

namespace mvc_rpg.Controllers
{
    public class ItemTypesController : Controller
    {
        private readonly RPGContext _context;

        public ItemTypesController(RPGContext context)
        {
            _context = context;
        }

        // GET: ItemTypes
        public async Task<IActionResult> Index()
        {
            return View(await _context.ItemTypes.ToListAsync());
        }

        // GET: ItemTypes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var itemType = await _context.ItemTypes
                .FirstOrDefaultAsync(m => m.ID == id);
            if (itemType == null)
            {
                return NotFound();
            }

            return View(itemType);
        }

        // GET: ItemTypes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ItemTypes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Name")] ItemType itemType)
        {
            if (ModelState.IsValid)
            {
                _context.Add(itemType);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(itemType);
        }

        // GET: ItemTypes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var itemType = await _context.ItemTypes.FindAsync(id);
            if (itemType == null)
            {
                return NotFound();
            }
            return View(itemType);
        }

        // POST: ItemTypes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Name")] ItemType itemType)
        {
            if (id != itemType.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(itemType);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ItemTypeExists(itemType.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(itemType);
        }

        // GET: ItemTypes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var itemType = await _context.ItemTypes
                .FirstOrDefaultAsync(m => m.ID == id);
            if (itemType == null)
            {
                return NotFound();
            }

            return View(itemType);
        }

        // POST: ItemTypes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var itemType = await _context.ItemTypes.FindAsync(id);
            if (itemType != null)
            {
                _context.ItemTypes.Remove(itemType);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ItemTypeExists(int id)
        {
            return _context.ItemTypes.Any(e => e.ID == id);
        }
    }
}

mvc-rpg/Controllers/PlayersController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Linq;
using System.Security.Policy;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using mvc_rpg.Data;
using mvc_rpg.Entities;

namespace mvc_rpg.Controllers
{
    public class PlayersController : Controller
    {
        private readonly RPGContext _context;
        private static readonly ImageConverter _imageConverter = new ImageConverter();
        public PlayersController(RPGContext context)
        {
            _context = context;
        }


        // GET: Players/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var detailModel = new mvc_rpg.ViewModel.PlayerDetail();
            var player = await _context.Players
                .Include(x => x.Items)
                    .ThenInclude(x => x.ItemType)
                .FirstOrDefaultAsync(m => m.ID == id);

            detailModel.Player = player;

            var graves = _context.Graves
                .Include(m => m.Player)
                .Include(m => m.Enemy)
                .Where(m => m.PlayerID == id)
                .ToList();

            detailModel.Graves = graves;

            if (player == null)
            {
                return NotFound();
            }

            return View(detailModel);
        }

        // GET: Players/Create
        public IActionResult Index()
        {
            return View();
        }

        public static byte[] ImageToByte(Image img)
        {
            ImageConverter converter = new ImageConverter();
            return (byte[])converter.ConvertTo(img, typeof(byte[]));
        }

        public static Bitmap GetImageFromByteArray(byte[] byteArray)
        {
            Bitmap bm = (Bitmap)_imageConverter.ConvertFrom(byteArray);

            if (bm != null && (bm.HorizontalResolution != (int)bm.HorizontalResolution ||
                               bm.VerticalResolution != (int)bm.VerticalResolution))
            {
                // Correct a strange glitch that has been observed in the test program when converting 
                //  from a PNG file image created by CopyImageToByteArray() - the dpi value "drifts" 
                //  slightly away from the nominal integer value
                bm.SetResolution((int)(bm.HorizontalResolution + 0.5f),
                                 (int)(bm.VerticalResolution + 0.5f));
            }

            return bm;
        }

        private static Bitmap ResizeImage(Bitmap imgToResize, Size size)
        {
            // Get the image current width
            int sourceWidth = imgToResize.Width;
            // Get the image current height
            int sourceHeight = imgToResize.Height;
            float nPercent = 0;
            float nPercentW = 0;
            float nPercentH = 0;
            // Calculate width and height with new desired size
            nPercentW = ((float)size.Width / (float)sourceWidth);
            nPercentH = ((float)size.Height / (float)sourceHeight);
            nPercent = Math.Min(nPercentW, nPercentH);
            // New Width and Height
            int destWidth = (int)(sourceWidth * nPercent);
            int destHeight = (int)(sourceHeight * nPercent);
            Bitmap b = new Bitmap(destWidth, destHeight);
            Graphics g = Graphics.FromImage((System.Drawing.Image)b);
            g.InterpolationMode = InterpolationMode.HighQualityBicubic;
            // Draw image with new width and height
            g.DrawImage(imgToResize, 0, 0, destWidth, destHeight);
            g.Dispose();
            return (Bitmap)b;
        }

        private byte[] GetByteArrayFromImage(IFormFile file)
        {
            using (var target = new MemoryStream())
            {
                file.CopyTo(target);
                return target.ToArray();
            }
        }

        // POST: Players/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create( Player player)
        {
            if (player.Name == "Admin")
            {
                HttpContext.Session.SetInt32("user_ID", -1);
                return Redirect("/Home/Admin");
            }

            if (player.ProfilePictureRaw != null)
            {
                player.ProfilePicture = GetByteArrayFromImage(player.ProfilePictureRaw);
            }
            player.isAlive = true;
            Bitmap bmp;
            using (var ms = new MemoryStream(player.ProfilePicture))
            {
                bmp = new Bitmap(ms);
            }

            bmp = ResizeImage(bmp, new Size(512, 512));


            if (player.ProfilePictureRaw != null)
            {
                player.ProfilePicture = ImageToByte(bmp);
            }

            if (ModelState.IsValid)
            {
                _context.Add(player);
                await _context.SaveChangesAsync();
                HttpContext.Session.SetInt32("user_ID", player.ID);
                return Redirect($"/Players/Details/{player.ID}");
            }
            return Redirect($"/Players/Details/{player.ID}");
        }

        // GET: Players/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var player = await _context.Players.FindAsync(id);
            if (player == null)
            {
                return NotFound();
            }
            return View(player);
        }

        // POST: Players/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Name,Health,SkinType,HairType,EyeType,ProfilePicture")] Player player)
        {
            if (id != player.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(player);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PlayerExists(player.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(player);
        }

        // GET: Players/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var player = await _context.Players
                .FirstOrDefaultAsync(m => m.ID == id);
            if (player == null)
            {
                return NotFound();
            }

            return View(player);
        }

        // POST: Players/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var player = await _context.Players.FindAsync(id);
            if (player != null)
            {
                _context.Players.Remove(player);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PlayerExists(int id)
        {
            return _context.Players.Any(e => e.ID == id);
        }
    }
}

mvc-rpg/Views/Home/Admin.cshtml
@model List<System.Linq.IGrouping<mvc_rpg.Entities.Player, mvc_rpg.Entities.Grave>>
@{
}
@if (Context.Session.GetInt32("user_ID") == -1)
{
    <a asp-action="Index" asp-controller="Enemies">Edit Enemies</a>
    <a asp-action="Index" asp-controller="EnemyTypes">Edit Enemy Types</a>
    <a asp-action="Index" asp-controller="ItemTypes">Edit Item Types</a>
} else
{
    <p>You do not have access to this page</p>
}

mvc-rpg/Views/Home/HallOfFame.cshtml
@model mvc_rpg.ViewModel.HallOfFame;
@{
}
<style>
    img {
        width:64px;
        height:64px;
    }

</style>

<h1 class="mb2" style="text-align:center"><b style="color:#0c69f0">Hall of fame.</h1>
<h3 style="text-align:center">Measuring the last 100 kills.</h3>
<hr>

@if (Model.page != 0)
{
    <a asp-action="HallOfFame" asp-route-searchTerm="@Model.Search" asp-route-page="@Model.subtractFromPage(Model.page)">◄</a>
}
<span>@Model.page</span>
@if (Context.Session.GetInt32("canTurn") == 1)
{
    <a asp-action="HallOfFame" asp-route-searchTerm="@Model.Search" asp-route-page="@Model.addToPage(Model.page)">►</a>
}

<div class="container mt2 text--gray">
    @foreach (var player in Model.Entries)
    {
        <div class="grid-column mb2 reveal-on-scroll is-revealing">
            <div>
            @{
                var base64 = Convert.ToBase64String(player.Key.ProfilePicture);
                var imgSrc = String.Format("data:image/gif;base64,{0}", base64);
                //Converted das ByteArray zu Base64 und converted es in ein bild.
            }
            <img src="@imgSrc" />
            <a asp-action="Details" asp-controller="Players" asp-route-id="@player.Key.ID">@player.Key.Name Killed @player.Count() Enemies</a>
            </div>
        </div>
    }
</div>

mvc-rpg/Views/Home/Index.cshtml
@model mvc_rpg.ViewModel.VersusScreen;
@{
    ViewData["Title"] = "Home Page";
}
<style>
    .enemy, .player {
        width: 40%;
        float: left;
        text-align: center;
        margin-left: 5%;
        margin-right: 5%;
        border-radius: 12px;
    }
</style>


<h1 class="mb2" style="text-align:center"><b style="color:#0c69f0">Battleground.</h1>
<hr/>
<a asp-action="Index" asp-controller="Home" style="text-align:center">Next Fight!</a>
<br/>
<br/>

@Html.ValidationMessageFor(m => m.Enemy)
@Html.ValidationMessageFor(m => m.Player)


<div class="enemy">
    @if (Model.Enemy != null)
    {
        <p>@Model.Enemy.EnemyType.Name | @Model.Enemy.Name</p>
        <img src="~/Default/img_defaultPicture.jpg" width="128" height="128" />
        <br>
        @if (Model.Enemy.isAlive == true)
        {
            <style>
                .enemy {
                    background-color:lightgreen;
                }
            </style>
            <p>WON</p>
        }
        else
        {
            <style>
                .enemy {
                   background-color:lightcoral;
                }
            </style>
            <p>LOST</p>
        }

    }
</div>

@if (Model.Player != null)
{
    <div class="player">
            @{
                var base64 = Convert.ToBase64String(Model.Player.ProfilePicture);
                var imgSrc = String.Format("data:image/gif;base64,{0}", base64);
                //Converted das ByteArray zu Base64 und converted es in ein bild.
            }

            <p>@Model.Player.Name </p>
            <img src="@imgSrc" width="128" height="128" />
            <br>
            @if (Model.Player.isAlive == true)
            {
                <style>
                    .player {
                        background-color: lightgreen;
                    }
                </style>
                <p>WON</p>
            }
            else
            {
                <style>
                    .player {
                        background-color: lightcoral;
                    }
                </style>
                <p>LOST</p>
            }
    </div>
    <div style="text-align:center">
        <p>Enemies Slain by this Player:</p>
        @foreach (var i in Model.PlayerKilledEnemies)
        {
            <div>@i.Enemy.Name</div>
        }
    </div>
    
}




<h1 class="mb2" style="text-align:center"><b style="color:#0c69f0">Combat Log.</h1>
<hr>
<div class="container mt2 text--gray">
    @foreach (var i in Model.Graves)
    {
        <div class="grid-column mb2 reveal-on-scroll is-revealing">
            <div>
                @if (i.KilledBy == killedBy.Enemy)
                {
                    <p>[@i.DateTime]: @i.Player.Name killed by @i.Enemy.Name</p>
                }
                else
                {
                    <p>[@i.DateTime]: @i.Enemy.Name killed by @i.Player.Name</p>
                }
            </div>
        </div>
    }
</div>

mvc-rpg/Views/Home/Inventory.cshtml
@model mvc_rpg.Entities.Player
@{
    ViewData["Title"] = "Inventory";
}
<p>This is your Inventory!</p>
@foreach(var item in Model.Items)
{
    <p>@item.Name</p>
}

mvc-rpg/Views/Home/SearchPlayer.cshtml
@model mvc_rpg.ViewModel.SearchPlayers
@{
    ViewData["Title"] = "Home Page";
}
<style>
    img {
        width:64px;
        height:64px;
    }

    /*! normalize.css v7.0.0 | MIT License | github.com/necolas/normalize.css */
    

</style>

<h1 class="mb2" style="text-align:center"><b style="color:#0c69f0">Search through all players.</b></h1>
<hr>
    <a asp-controller="Players" asp-action="Index">Create</a>
    <form asp-action="SearchPlayer" method="get">
        <div class="form-actions no-color align--center">
            <p>
                <input name="SearchTerm" class="form-control" value="@Model.Search"/>
                <input type="submit" value="Search" class="btn btn-primary align--center" />
            @if (Model.page != 0)
            {
                <a asp-action="searchPlayer" asp-route-searchTerm="@Model.Search" asp-route-page="@Model.subtractFromPage(Model.page)">◄</a>
            }            
            <span>@Model.page</span>
            @if (Context.Session.GetInt32("canTurn") == 1)
            {
                <a asp-action="searchPlayer" asp-route-searchTerm="@Model.Search" asp-route-page="@Model.addToPage(Model.page)">►</a>
            }
            </p>
        </div>
    </form>
    <!-- Feature list -->
    <div class="container mt2 text--gray">
        @foreach (var player in Model.Players)
        {
            <div class="grid-column mb2 reveal-on-scroll is-revealing">
                <div>
                @if (player.ProfilePicture != null)
                {
                    var base64 = Convert.ToBase64String(player.ProfilePicture);
                    var imgSrc = String.Format("data:image/gif;base64,{0}", base64);
                    //Converted das ByteArray zu Base64 und converted es in ein bild.
                    <img src="@imgSrc" />
                }
                <a asp-action="Details" asp-controller="Players" asp-route-id="@player.ID" >@player.Name</a>
                </div>
            </div>
        }     
    </div>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}